### ISSUE TITLE
Manjaro linux  - Not able to disconnect properly

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [morpheusthewhite/nordpy#26] opened 2019-11-25 13:59 UTC
**Before Posting an issue**
- Installed all needed dependencies and that you run `install.py` 
- Installed version: NordPy 1.3.2
- Installed with trizen

**The bug**
When I connect to any vpn and then diconnect my network is broken. I need todo a rebot to get my network working again.

**To Reproduce**
1. Install manjaro (with kde-PLASMA and kernel 4.19.85-1-MANJARO)
2. Install the latest nordpy with trizen
3. put in your credentials and leave all the settings to default-values
4. Connect to any server
5. Disconnect from any server

Sadly I did not know how I can give you some logs. If you tell me that I will do this.
It would be awesome if we can bring it to run. I did not change a lot on this manjaro install.

**Comment by morpheusthewhite** [comment] 2019-11-25 21:03
This is a problem I am myself encountering in the past weeks

**Comment by morpheusthewhite** [comment] 2019-11-25 21:06
It is caused by the DNS configuration (which is set up by manually modifying the `resolv.conf` file after some DNS leaks). I need to find a workaround for using `resolvconf` or `autoconf` on all systems (which I had previously used by had problems in private networks which presented a login page)

**Comment by morpheusthewhite** [comment] 2019-11-26 07:08
At the moment I am not able to replicate the problem.

Can you provide me the following informations?

1. DNS configuration before VPN connection (just `cat /etc/resolv.conf`)
2. Iptables before VPN connection (`sudo iptables --list`)
3. DNS configuration after VPN connection
4. Iptables after VPN connection
5. What is the connection error when you open a browser?
6. What is the output of `ping github.com`? What is the output of `ping 8.8.8.8`?

**Comment by MuffinCollector** [comment] 2019-12-14 00:35
I've been dealing with this on and off as well on my Arch installation. I can't seem to reproduce at the moment, but last time I experienced this, I checked my resolv.conf and it looked appropriate (contained my router address which I use as my DNS server and is how it normally appears when not connected) and my iptables list. iptables when not connected for me is blank. When I became unable to connect to the internet, it instead appeared to be the same as when I'm connected to my VPN. While I failed to note the specifics at that time, I was able to regain my connection without reboot by flushing iptables and then restarting the iptables service.

**Comment by morpheusthewhite** [comment] 2020-02-28 20:49
This should be fixed with https://github.com/morpheusthewhite/nordpy/commit/80ab4f9477ca80b9f670af015e47279e3271498d

**Comment by larry77** [comment] 2020-03-09 11:21
I am experiencing the same issue on debian stable + wicd network manager + TCP when the wifi goes down.
If it happens again, I will post more.

**Comment by morpheusthewhite** [comment] 2020-03-09 12:43
Are you using the latest version?

**Comment by morpheusthewhite** [comment] 2020-03-09 12:45
Oh wait if the wifi goes down and then comes back again I think it's obvious it won't work, it's actually a problem related to `openvpn`

**Comment by larry77** [comment] 2020-03-09 13:54
yes,  I am using the latest version. I have issues even if I just disconnect from the vpn using the app.
Before the vpn connection

~$ cat /etc/resolv.conf
domain hotspot.ec.europa.eu
search hotspot.ec.europa.eu
nameserver 147.67.12.18
nameserver 147.67.250.18

~$ sudo iptables --list
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination 


After the VPN connection (TCP)

~$ cat /etc/resolv.conf
# Appended by NordPy
nameserver 103.86.96.100
nameserver 103.86.99.100
domain hotspot.ec.europa.eu
search hotspot.ec.europa.eu

~$ sudo iptables --list
Chain INPUT (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  172.17.192.0/18      anywhere            
ACCEPT     tcp  --  5.180.62.93          anywhere             tcp spt:https
ACCEPT     all  --  anywhere             anywhere            

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             172.17.192.0/18     
ACCEPT     tcp  --  anywhere             5.180.62.93          tcp dpt:https
ACCEPT     all  --  anywhere             anywhere            
# Warning: iptables-legacy tables present, use iptables-legacy to see them


~$ sudo iptables-legacy --list
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

**Comment by larry77** [comment] 2020-03-09 14:03
I cannot reproduce the issue easily. It appears that part of the problem was my closing the app instead of properly disconnecting. I will post more when (if) this becomes fully reproducible on my system.

**Comment by morpheusthewhite** [comment] 2020-03-09 15:05
Closing the application should not cause any problems since all needed information are stored in files

**Comment by larry77** [comment] 2020-03-10 08:53
Hello,
Again, after losing the connection there was no way I could re-establish it (with or without vpn).
Wicd told me I was connected, nordpy said I was not and finally the only way to get back online was a full reboot.
Before that I tried disconnecting manually using nordpy's interface and reconnecting and this is what I saw on the console

``
Turning off killswitch
looking for iptables in /home/lorenzo/nordpy-master/stored_iptables
Selected a particular country: Germany
resulting url: https://nordvpn.com/wp-admin/admin-ajax.php?action=servers_recommendations&filters={%22servers_groups%22:11,%22country_id%22:81}
Selected a particular country: Germany
resulting url: https://nordvpn.com/wp-admin/admin-ajax.php?action=servers_recommendations&filters={%22servers_groups%22:11,%22country_id%22:81}
``

but finally I was not able to get back online.

**Comment by morpheusthewhite** [comment] 2020-04-17 07:40
@larry77 are you experiencing this problem only when the wifi goes down?

**Comment by larry77** [comment] 2020-04-17 08:00
Hello,
I experienced this mostly at work with a wifi connection.
The connection used to go down every now and then for a few seconds only.

**Closed** 2020-04-17 08:45 UTC
Labels: bug, environment, help wanted
